# Generated by Django 5.0.7 on 2025-04-09 13:47

import django.db.models.deletion
import isar.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Regiao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos docs',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('foto', models.FileField(upload_to=isar.models.uploadFotoImovel)),
                ('cep', models.CharField(max_length=8)),
                ('logradouro', models.CharField(max_length=512)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.TextField(blank=True, null=True)),
                ('largura', models.FloatField()),
                ('comprimento', models.FloatField()),
                ('area', models.FloatField(default=0)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isar.bairro')),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isar.cidade')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isar.estado')),
                ('regiao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isar.regiao')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isar.tipo')),
            ],
            options={
                'verbose_name_plural': 'Imoveis',
            },
        ),
        migrations.CreateModel(
            name='ImagemImovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=isar.models.uploadFotoImovel)),
                ('descricao', models.TextField()),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isar.imovel')),
            ],
            options={
                'verbose_name_plural': 'Imagens imoveis',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_doc', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isar.tipo_doc')),
            ],
        ),
    ]
